repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: Black code formatter
        language_version: python3
        args: ["--line-length=120"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]

  - repo: local
    hooks:
      - id: mapctl-validate
        name: mapctl validate
        entry: python tools/mapctl.py validate
        language: system
        pass_filenames: false  # Не передавать файлы как аргументы!
