name: Unity CI

on:
  push:
    branches: [ main, feature/** ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
      - name: dotnet build
        run: dotnet build
      - name: Unity EditMode tests
        run: |
          unity -batchmode -runTests -projectPath . -testResults results_EditMode.xml -testPlatform EditMode
      - name: Unity PlayMode tests
        run: |
          unity -batchmode -runTests -projectPath . -testResults results_PlayMode.xml -testPlatform PlayMode
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: unity-test-results
          path: |
            results_EditMode.xml
            results_PlayMode.xml
